site_name: MADS
site_url: http://madsjulia.lanl.gov
theme: readthedocs

repo_url: https://github.com/madsjulia/Mads.jl
site_description: "Model Analysis and Decision Support"
site_author: "Velimir monty Vesselinov"
site_favicon: mads-favicon.ico

pages:
- Home: index.md
- Installation: INSTALLATION.md
- Getting started: GETTING_STARTED.md
- Examples:
  - Setup: EXAMPLES_SETUP.md
  - Decision Analysis: Examples/bigdt/source_termination/source_termination.md
  - Bayesian sampling: Examples/bayesian_sampling/bayesian_sampling.md
- Model coupling: MODEL_COUPLING.md
- Testing & Verification: TEST.md
- Functions: FUNCTIONS.md
- Modules:
  - Mads: Modules/Mads.md
  - BIGUQ: Modules/BIGUQ.md
  - Anasol: Modules/Anasol.md
  - ReusableFunctions: Modules/ReusableFunctions.md
  - MetaProgTools: Modules/MetaProgTools.md
  - RobustPmap: Modules/RobustPmap.md
- Acknowledgments: ACKNOWLEDGMENTS.md
- License: COPYING.md

markdown_extensions:
  - extra
  - tables
  - toc
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
  - footnotes

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']