site_name: MADS
site_url: http://mads.readthedocs.io
theme: material

repo_url: https://github.com/madsjulia/Mads.jl
site_description: "Model Analysis and Decision Support"
site_author: "Velimir monty Vesselinov"
site_favicon: mads-favicon.ico

extra_css:
- assets/Documenter.css

pages:
- Home: index.md
- Installation: INSTALLATION.md
- Getting started: GETTING_STARTED.md
- Examples:
  - Setup: EXAMPLES_SETUP.md
  - Decision Analysis: Examples/bigdt/source_termination/index.md
  - Information Gap Analysis: Examples/infogap/index.md
  - Bayesian Sampling: Examples/bayesian_sampling/index.md
  - Blind Source Separation: Examples/blind_source_separation/index.md
  - Contaminant Transport: Examples/contamination/index.md
  - ODE Analysis: Examples/ode/index.md
- Model Coupling: MODEL_COUPLING.md
- Testing & Verification: TEST.md
- Functions: FUNCTIONS.md
- Modules:
  - Mads: Modules/Mads.md
  - BIGUQ: Modules/BIGUQ.md
  - Anasol: Modules/Anasol.md
  - ReusableFunctions: Modules/ReusableFunctions.md
  - MetaProgTools: Modules/MetaProgTools.md
  - RobustPmap: Modules/RobustPmap.md
- Acknowledgments: ACKNOWLEDGMENTS.md
- License: COPYING.md

markdown_extensions:
  - extra
  - tables
  - toc
  - footnotes
  - admonition
  - codehilite
  - fenced_code
  - mdx_math:
    - enable_dollar_delimiter: True #for use of inline $..$


extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
#  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

extra:
  author:
    github: montyvesselinov