site_name: MADS
site_url: http://madsjulia.lanl.gov
theme: readthedocs

repo_url: https://github.com/madsjulia/Mads.jl
site_description: "Model Analysis and Decision Support"
site_author: "Velimir monty Vesselinov"
site_favicon: mads-favicon.ico

pages:
- Home: index.md
- Modules:
    - Mads: Modules/Mads.md
    - BIGUQ: Modules/BIGUQ.md
    - Anasol: Modules/Anasol.md
    - ReusableFunctions: Modules/ReusableFunctions.md
    - MetaProgTools: Modules/MetaProgTools.md

markdown_extensions:
    - tables
    - toc
    - fenced_code